### ISSUE TITLE
Фото макгрегора

### ISSUE THREAD

**Issue by VolodymyrTsimbalistyi** [VolodymyrTsimbalistyi/Voice05#2]
Фото макгрегора.
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwimyd2uhOzlAhUT7KYKHWloDdMQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.novayagazeta.ru%2Farticles%2F2019%2F03%2F28%2F80028-biznes-kloun&psig=AOvVaw2jLj6JMm6tCJkmuIC-W6hr&ust=1573901026535085

**Comment by ghost** [comment]
![0_UFC-229-Khabib-v-McGregor](https://user-images.githubusercontent.com/57795524/68938355-3e0e0980-07af-11ea-994c-bed346b05996.jpg)
